# Generated by Django 5.2 on 2025-05-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
