# Generated by Django 5.2 on 2025-05-08 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='max_uses',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='productunit',
            name='secret_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='productunit',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
