# Generated by Django 5.2 on 2025-05-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productunit_max_uses_productunit_secret_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productunit',
            old_name='usage_count',
            new_name='verification_attempts',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='secret_code',
        ),
    ]
