# Generated by Django 5.2 on 2025-05-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_usage_count_productunit_verification_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=255)),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='products.productunit')),
            ],
        ),
    ]
